### ISSUE TITLE
[FEATURE] Make the application properly deployable

### ISSUE THREAD

**Issue by sicklybeans** [sicklybeans/sjb_todo#4]
It's not clear what the best tool for this is yet. Maybe pip. Make the application deployable in a way that allows for easy versioning/updating/removal etc

**Comment by sbryant1014** [comment]
See the pythonic project structure guidelines: http://docs.python-guide.org/en/latest/writing/structure/

In particular pay attention to the Pip requirements file: https://pip.pypa.io/en/stable/user_guide/#requirements-files

You should first complete issue #29, since these will likely affect one another

**Comment by sbryant1014** [comment]
Also definitely look into the sublime requirements.txt package for dealing with that guy
